server:
  port: 8010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: localhost:8848
#      routes:
#        - id: provider_route
#          uri: http://localhost:8083
#          predicates:
#            - Path=/provider/**
#          filters:
#            - StripPrefix=1
