spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false
  application:
    name: provider
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        exclude: '*'